#!/usr/bin/env python3
"""Generate test_hdlc_vectors.h from marilib's HDLC encoder.

The gateway's hdlc.c decodes what marilib's hdlc_encode produces, so the
vectors the C decoder is tested against are built by the other implementation
rather than by a second copy of the same logic. Run from this directory with
the repo's marilib on the path:

    PYTHONPATH=../../../marilib python3 test_hdlc_vectors.py > test_hdlc_vectors.h
"""

import sys

from marilib.serial_hdlc import hdlc_encode

FLAG = 0x7E
ESCAPE = 0x7D


def fcs_bytes(payload: bytes) -> bytes:
    """The two FCS bytes hdlc_encode appends, before escaping."""
    encoded = hdlc_encode(payload)
    # strip flags, unescape, keep the last two bytes
    body = bytearray()
    escaped = False
    for byte in encoded[1:-1]:
        if escaped:
            body.append(byte ^ 0x20)
            escaped = False
        elif byte == ESCAPE:
            escaped = True
        else:
            body.append(byte)
    return bytes(body[-2:])


def find_payload_with_escaped_fcs() -> bytes:
    """A payload whose FCS itself needs escaping, so the tail is exercised."""
    for i in range(1 << 16):
        payload = b"probe" + i.to_bytes(2, "little")
        if any(b in (FLAG, ESCAPE) for b in fcs_bytes(payload)):
            return payload
    raise SystemExit("no payload with an escaped FCS byte found")


SIMPLE = bytes.fromhex("0310170059291ba8fdcecef531eb7f2526ef0399") + b"\xf0" * 5
ESCAPES = b"\x7e\x7d start " + bytes(range(0x7A, 0x80)) + b" end \x7d\x7e"
MAXIMUM = bytes((i * 7 + 3) & 0xFF for i in range(255))
FCS_ESCAPED = find_payload_with_escaped_fcs()


def stream(*payloads: bytes) -> bytes:
    return b"".join(hdlc_encode(p) for p in payloads)


def truncated(payload: bytes, keep: int) -> bytes:
    """A frame cut short: no closing flag, so the next flag ends it as garbage."""
    return bytes(hdlc_encode(payload))[:keep]


def corrupted(payload: bytes) -> bytes:
    """A complete, flag-delimited frame with one payload byte flipped."""
    frame = bytearray(hdlc_encode(payload))
    frame[3] ^= 0xFF
    return bytes(frame)


# name, stream, expected decoded frames, expected MR_HDLC_STATE_ERROR transitions
VECTORS = [
    ("one frame", stream(SIMPLE), [SIMPLE], 0),
    ("two frames back to back", stream(SIMPLE, ESCAPES), [SIMPLE, ESCAPES], 0),
    (
        "four frames in one stream",
        stream(SIMPLE, ESCAPES, FCS_ESCAPED, SIMPLE),
        [SIMPLE, ESCAPES, FCS_ESCAPED, SIMPLE],
        0,
    ),
    ("escaped flag and escape bytes", stream(ESCAPES), [ESCAPES], 0),
    ("escaped fcs byte", stream(FCS_ESCAPED), [FCS_ESCAPED], 0),
    ("max size mari packet", stream(MAXIMUM), [MAXIMUM], 0),
    # A frame carrying nothing but its FCS decodes to zero bytes, which the
    # gateway treats as no frame at all rather than as an empty one.
    ("empty payload yields no frame", stream(b""), [], 0),
    # A frame with no closing flag is ended by the next frame's opening flag,
    # which fails the FCS. The bytes of that next frame are then dropped until
    # its own closing flag, which opens a fresh frame - so one truncation costs
    # the frame after it as well, and the stream resyncs from the third.
    (
        "truncation costs the next frame, then resyncs",
        truncated(SIMPLE, 10) + stream(ESCAPES, FCS_ESCAPED, SIMPLE),
        [FCS_ESCAPED, SIMPLE],
        1,
    ),
    # A corrupted but properly delimited frame costs only itself.
    (
        "corrupted frame costs only itself",
        corrupted(SIMPLE) + stream(ESCAPES),
        [ESCAPES],
        1,
    ),
    (
        "corruption in the middle of a run",
        stream(SIMPLE) + corrupted(ESCAPES) + stream(FCS_ESCAPED),
        [SIMPLE, FCS_ESCAPED],
        1,
    ),
    # Bytes that never open a frame are ignored rather than misread.
    (
        "leading noise before the first flag",
        bytes([0x11, 0x22, 0x33]) + stream(SIMPLE),
        [SIMPLE],
        0,
    ),
]


def c_bytes(data: bytes) -> str:
    if not data:
        return "    0x00,  /* unused, C forbids a zero-length array */"
    lines = []
    for start in range(0, len(data), 12):
        chunk = data[start : start + 12]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    return "\n".join(lines)


def emit(out) -> None:
    print("/* Generated by test_hdlc_vectors.py from marilib's hdlc_encode. */", file=out)
    print("/* Do not edit by hand; regenerate instead. */", file=out)
    print("#ifndef __TEST_HDLC_VECTORS_H", file=out)
    print("#define __TEST_HDLC_VECTORS_H", file=out)
    print("", file=out)
    print("#include <stddef.h>", file=out)
    print("#include <stdint.h>", file=out)
    print("", file=out)

    for idx, (_, stream_bytes, frames, _) in enumerate(VECTORS):
        print(f"static const uint8_t vec{idx}_stream[] = {{", file=out)
        print(c_bytes(stream_bytes), file=out)
        print("};", file=out)
        # C forbids zero-length arrays, so a vector expecting no frame still
        # gets one placeholder entry; frame_count is what the test reads.
        for fidx, frame in enumerate(frames or [b""]):
            print(f"static const uint8_t vec{idx}_frame{fidx}[] = {{", file=out)
            print(c_bytes(frame), file=out)
            print("};", file=out)
        count = max(len(frames), 1)
        joined = ", ".join(f"vec{idx}_frame{f}" for f in range(count))
        print(f"static const uint8_t *const vec{idx}_frames[] = {{ {joined} }};", file=out)
        lens = ", ".join(str(len(f)) for f in (frames or [b""]))
        print(f"static const size_t vec{idx}_frame_lens[] = {{ {lens} }};", file=out)
        print("", file=out)

    print("typedef struct {", file=out)
    print("    const char          *name;", file=out)
    print("    const uint8_t       *stream;", file=out)
    print("    size_t               stream_len;", file=out)
    print("    const uint8_t *const *frames;", file=out)
    print("    const size_t        *frame_lens;", file=out)
    print("    size_t               frame_count;", file=out)
    print("    size_t               expected_errors;", file=out)
    print("} hdlc_vector_t;", file=out)
    print("", file=out)
    print("static const hdlc_vector_t HDLC_VECTORS[] = {", file=out)
    for idx, (name, stream_bytes, frames, errors) in enumerate(VECTORS):
        print(
            f'    {{ "{name}", vec{idx}_stream, {len(stream_bytes)}, '
            f"vec{idx}_frames, vec{idx}_frame_lens, {len(frames)}, {errors} }},",
            file=out,
        )
    print("};", file=out)
    print("", file=out)
    print("#endif", file=out)


if __name__ == "__main__":
    emit(sys.stdout)
