name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build applications
        run: make docker
