name: Check Clang Format

on:
    push:
      branches:
        - main
      tags:
        - '*'
    pull_request:
  
jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt install clang-format

      - name: Check C/H files formatting (skip nRF)
        run: |
          find app drv mira \( -name "*.c" -o -name "*.h" \) \
            -exec clang-format --dry-run --Werror {} +